"""Global variables"""

DEFAULT_CHARACTER_SIZE = (23, 30)
WALK_FRAME_DELAY_NORMAL = 5
WALK_FRAME_DELAY_BORDER = 20
DAMAGE_DISPLAY_FRAMES = 15
ATTACK_DISPLAY_FRAMES = 10

DEFAULT_WINDOW_SIZE = (640, 480)
DEFAULT_WALL_THICKNESS = 20
DEFAULT_CELL_SIZE = 80
DEFAULT_NUM_WALLS = 6
DEFAULT_MIN_WALL_SIZE = 40
DEFAULT_MAX_WALL_SIZE = 200
DEFAULT_DEATH_FADE_DURATION = 5.0
